# get the ubuntu
FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04
# get the python


#Get the docs
# install the reqs with pip 


# install cv2 with conda 
# conda install opencv-python==4.4.0.42

# Michi says that you can install cv2 with CONDA
# you can also install the Pillow with the pytho
